[json_storage]
file_path = "common_todo_db.json"

[postgres]
address = "localhost:5432"
username = "admin"
password = "admin"
database = "todoapp"
table = "tasks"

[mongodb]
port = "27017"
address = "localhost"
username = "admin"
password = "admin"
database = "todoapp"
collection = "tasks"
